apiVersion: v1
kind: Service
metadata:
  name: nginx-deployment
  labels:
    run: nginx
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  type: LoadBalancer
